server:
  log_level: debug

logs:
    configs:
      - name: loki
        positions:
          filename: /tmp/positions.yaml
          sync_period: 15s
        clients:
          - url: http://loki:3100/loki/api/v1/push
            external_labels:
              job: agent
        scrape_configs:
          - job_name: varlogs
            static_configs:
              - targets: [localhost]
                labels:
                  job: varlogs
                  __path__: /var/log/*log
          - job_name: dmesg
            static_configs:
              - targets: [localhost]
                labels:
                  job: dmesg
                  __path__: /var/log/dmesg