server:
  log_level: debug

# Configures metrics job to scrape from the ClickHouse server
metrics:
  wal_directory: /tmp/grafana-agent/wal
  global:
    scrape_interval: 60s
    remote_write:
      - url: http://mimir:9009/api/v1/push

  configs:
    - name: mimir-metrics
      # Scrape mimir metrics
      scrape_configs:
        - job_name: 'mimir-metrics'
          metrics_path: /metrics
          scrape_interval: 60s
          scrape_timeout: 5s
          static_configs:
            - targets: [ mimir:9009 ]

integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true