server:
  log_level: debug

# Configures metrics job to scrape from the ClickHouse server
metrics:
  wal_directory: /tmp/grafana-agent/wal
  global:
    scrape_interval: 60s
    # Configure the metrics remote write end point
    remote_write:
      - url: ${GRAFANA_METRICS_WRITE_URL_1}
        basic_auth:
          password: ${GRAFANA_METRICS_API_KEY_1}
          username: ${GRAFANA_METRICS_USERNAME_1}
  configs:
    - name: agent
      scrape_configs:
        - job_name: metrics_generator
          scrape_interval: 60s
          static_configs:
            - targets: ['metrics-generator1:8001']
              labels:
                group: 'test_metrics1'
        - job_name: agent1
          static_configs:
            - targets: ["127.0.0.1:12345"]
  