{
 "title": "example-job-status-1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "VAR_JOB_NAME",
    "query": {
     "query": "label_values(job_event_counter_total{},name)"
    }
   },
   {
    "name": "VAR_JOB_STATE",
    "query": {
     "query": "label_values(job_event_counter_total{},state)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "job_state_num{name=~\"$VAR_JOB_NAME\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Streaming Job Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"job-status\"} |= `` | json | name=~\"$VAR_JOB_NAME\" | state=~\"$VAR_JOB_STATE\" | line_format \"{{.name}} {{.state}}\""
    }
   ]
  },
  {
   "title": "Job Status Events",
   "type": "logs",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"job-event\"} |= `` | json | name=~\"$VAR_JOB_NAME\" | state=~\"$VAR_JOB_STATE\" | line_format \"{{.name}} {{.state}} {{.time_in_state}}\""
    }
   ]
  },
  {
   "title": "Avg Over  Time in Event State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (name, state) ( avg_over_time( {job=\"job-event\", name=~\"$VAR_JOB_NAME\", state=~\"$VAR_JOB_STATE\"} [5m] | json | unwrap time_in_state ) )",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Time Spent In State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "job_time_in_state{name=~\"$VAR_JOB_NAME\", state=~\"$VAR_JOB_STATE\"}",
     "legendFormat": "{{name}}-{{state}}"
    }
   ]
  },
  {
   "title": "Max Over  Time in Event State",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 13, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name, state) ( max_over_time( {job=\"job-event\", name=~\"$VAR_JOB_NAME\", state=~\"$VAR_JOB_STATE\"} [5m] | json | unwrap time_in_state ) )",
     "legendFormat": "{{name}} - {{state}}"
    }
   ]
  },
  {
   "title": "Total Events",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name, state) ( job_event_counter_total{name=~\"$VAR_JOB_NAME\", state=~\"$VAR_JOB_STATE\"} )",
     "legendFormat": "{{name}}: {{state}}"
    }
   ]
  },
  {
   "title": "Total Time In State (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "job_state_time_total{name=~\"$VAR_JOB_NAME\"}",
     "legendFormat": "{{name}}-{{state}}"
    }
   ]
  },
  {
   "title": "State Enum",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "job_state_num{name=~\"$VAR_JOB_NAME\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (name, state) (job_state_info{} )",
     "legendFormat": "{{name}}-{{state}}"
    }
   ]
  }
 ]
}