server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml
  sync_period: 15s

clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      job: promtail

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        source: promtail
        __path__: /var/log/*log
  - job_name: pushapi
    loki_push_api:
      server:
        http_listen_port: 3501
        grpc_listen_port: 3600
      labels:
        pushserver: pushapi
  # https://grafana.com/docs/loki/latest/clients/promtail/scraping/#syslog-ng-output-configuration
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:16602
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog1"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_severity']
        target_label: level
      - source_labels: ['__syslog_message_app_name']
        target_label: app_name
      - source_labels: [__syslog_message_facility]
        target_label: facility