version: "3.9"

services:

  # https://hub.docker.com/_/postgres
  postgres-server:
    image: postgres:latest@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome1 
    volumes:
      - "./dvdrental.tar:/dvdrental.tar"
      - "./ctl.sh:/ctl.sh"
      - "./postgres/postgresql.conf:/postgresql.conf"
      - "./logs/:/var/log/postgresql/"
    entrypoint:
      - "/ctl.sh"
      - "run"
      #- "sleep"


  # https://www.adminer.org/
  # Login localhost:8080 PostgreSQL / postgres-server / postgres / welcome1
  adminer:
    image: adminer@sha256:f742dcf1b6ca95733b54c4e020488ce78f3e774d73543a6ded9b4eaea8974f3d
    restart: always
    ports:
      - 8080:8080

  # Generate Prometheues Metrics from PostgresSQL
  # https://github.com/prometheus/client_python
  postgres-metrics:
    image: postgres-metrics/postgres-metrics
    build: ./postgres-metrics
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3600
        window: 30s
    environment:
      - PROMTHEUS_HTTP_PORT=8001
    ports:
      - "8001:8001"
    command: [ "7200", "60", "15", "postgres-server" ]

  # Grafana Agent
  # https://grafana.com/docs/agent/latest/
  grafana-agent:
    image: grafana/agent:latest@sha256:473928c1cace5a23fdb1c187dba4ec0fe733d4627ae65383861a7beb997db88c
    ports:
      - "12345:12345"
      - "12346:12346"
    volumes:
      - "./configured-config-cloud.yaml:/etc/agent/agent.yaml"
      - "./logs/:/logs"
    command: [ "-config.file=/etc/agent/agent.yaml" ]