{
 "title": "Postgres DVD Example1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Customer Payments by customer_id",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (customer_id) (dvd_payments{})",
     "legendFormat": "{{customer_id}}"
    }
   ]
  },
  {
   "title": "Queries by Host",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dvd_samples_total{}", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "SQL Durations",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |= \"duration:\""
    }
   ]
  },
  {
   "title": "SQL Statements",
   "type": "logs",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"} |= \"statement:\""
    }
   ]
  }
 ]
}