{
 "title": "Pyroscope Usage 1",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Rate Per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (type) (rate( pyroscope_distributor_received_decompressed_bytes_sum{} [5m] ) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Per Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate( pyroscope_distributor_received_decompressed_bytes_sum{} [5m] ) * 60 * 60 * 24 * 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (type) (rate( pyroscope_distributor_received_decompressed_bytes_sum{} [5m] ) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Per Month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate( pyroscope_distributor_received_decompressed_bytes_sum{} [5m] ) * 60 * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raw",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (type) (pyroscope_distributor_received_decompressed_bytes_sum{} )",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}