version: "3.8"
volumes:
  grafana:

services:

  # Grafana for exploring and visualizing data
  grafana-server-1:
    image: grafana/grafana:latest@sha256:2d1f9ae67c1778d33e291d4c3c759cd8b650e67491f02533499eb950e075eeb5
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - "3001:3000"

   # Grafana Metrics
  mimir:
    image: grafana/mimir:latest@sha256:4508fd612969dfcf4b50276856fd05d5a971b15e494ad53da911b44781446f2b
    depends_on:
      - grafana-server-1
    volumes:
      - "./mimir/config-single.yaml:/etc/mimir/config.yaml"
    ports:
      - "9009:9009"
    command: [
      "-config.file=/etc/mimir/config.yaml"
    ]

  # Grafana Agent
  grafana-agent:
    image: grafana/agent:latest@sha256:473928c1cace5a23fdb1c187dba4ec0fe733d4627ae65383861a7beb997db88c
    depends_on:
      - mimir
    ports:
      - "12345:12345"
      - "3500:3500"
      - "16603:16603"
    volumes:
      - "./grafana-agent/config.yaml:/etc/agent/agent.yaml"
    command: [
      "-config.file=/etc/agent/agent.yaml",
      "-server.http.address=0.0.0.0:12345",
    ]