version: "3.8"
volumes:
  grafana:

services:

  # Grafana Enterprise
  grafana-server:
    image: grafana/grafana-enterprise@sha256:06f65b30ff6513f55316beb6ff3e22d0132189297032ada2dfdc116f95663a60
    container_name: grafana-server
    environment:
      - GF_INSTALL_PLUGINS=grafana-splunk-datasource
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      #- "./grafana/provisioning:/etc/grafana/provisioning"
      - "./ge-license.jwt:/var/lib/grafana/license.jwt"
    ports:
      - "3000:3000"

   # Splunk Enterprise
  splunk-enterprise:
    image: splunk/splunk:latest@sha256:9280f9ce267b212e5596aa1832cdfd3f9be886c378da35ebc87499323ee447a4
    container_name: splunk-enterprise
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=welcome1
    ports:
      - "8000:8000"
      - "8065:8065"
      - "8088-8089:8088-8089"
      - "8191:8191"
      - "9887:9887"
      - "9997:9997"




 