version: "3.8"
volumes:
  grafana:

services:

  # Grafana Enterprise
  grafana-server:
    image: grafana/grafana-enterprise@sha256:9d4017a1a3b480262281dc24f143af64c3de26b8c934d4bc3ab0d4e30ee3a476
    container_name: grafana-server
    environment:
      - GF_INSTALL_PLUGINS=grafana-splunk-datasource
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      #- "./grafana/provisioning:/etc/grafana/provisioning"
      - "./ge-license.jwt:/var/lib/grafana/license.jwt"
    ports:
      - "3000:3000"

   # Splunk Enterprise
  splunk-enterprise:
    image: splunk/splunk:latest@sha256:77183a6c0c616d736aa2538e3dbacfe8fe3a1950ea174c70c4402e70d4159ae8
    container_name: splunk-enterprise
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=welcome1
    ports:
      - "8000:8000"
      - "8065:8065"
      - "8088-8089:8088-8089"
      - "8191:8191"
      - "9887:9887"
      - "9997:9997"




 