version: "3.8"
volumes:
  grafana:

services:

  # Grafana Enterprise
  grafana-server:
    image: grafana/grafana-enterprise@sha256:a297072de9f2f02e52166cf853281d1478e94d738e4e1905938c4257f59d88b3
    container_name: grafana-server
    environment:
      - GF_INSTALL_PLUGINS=grafana-splunk-datasource
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      #- "./grafana/provisioning:/etc/grafana/provisioning"
      - "./ge-license.jwt:/var/lib/grafana/license.jwt"
    ports:
      - "3000:3000"

   # Splunk Enterprise
  splunk-enterprise:
    image: splunk/splunk:latest@sha256:cc3a3efe2509fa31f67d4aa20dde7118886babf9a0930f197ef996d513c44834
    container_name: splunk-enterprise
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=welcome1
    ports:
      - "8000:8000"
      - "8065:8065"
      - "8088-8089:8088-8089"
      - "8191:8191"
      - "9887:9887"
      - "9997:9997"




 