server:
  log_level: debug

# Configures metrics job to scrape ...
metrics:
  wal_directory: /tmp/grafana-agent/wal
  configs:
    - name: agent
      scrape_configs:
        - job_name: agent
          static_configs:
            - targets: ["127.0.0.1:12345"]
      remote_write:
        - url: http://mimir:9009/api/v1/push
                
integrations:
  agent:
    enabled: true
  node_exporter:
    enabled: true