# Grafana Cloud Configuration

export GRAFANA_CLOUD_OTEL_EXPORTER_OTLP_ENDPOINT=<REQUIRED>
export GRAFANA_CLOUD_OTLP_INSTANCE_ID=<REQUIRED>
export GRAFANA_CLOUD_OTLP_PASSWORD=<REQUIRED>

export GRAFANA_METRICS_HOST="prometheus-<REQUIRED>.grafana.net"
export GRAFANA_METRICS_USERNAME=<REQUIRED>
export GRAFANA_METRICS_WRITE_URL="https://$GRAFANA_METRICS_HOST/api/prom/push"
export GRAFANA_METRICS_API_KEY=<REQUIRED>

PROMETHEUS_SCRAPE_NODE=simplemetric-generator:8001

METRIC_GEN_SIMPLE_TRACE_ID=280500b9cb4529ca3e969c3825bad358
