{
 "title": "0000 - Cost Management - Visualize Usage Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"color:#fffff;font-size: 16px\">\nThis dashboard illustrates the visualization of each of the usage metrics in a time series panel\n</p>\n<p style=\"color:#fffff;font-size: 16px\">\nTake each metric in turn and add it to a Time Series panel with the grafanacloud-usage datasource\n</p>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "options": {
    "content": "<p style=\"color:#fffff;font-size: 16px\">\n  Grafana Cloud Usage Metrics\n<p>\n<p style=\"color:#fb755aff;font-size: 16px\">\ngrafanacloud_org_metrics_billable_series{}<br>\ngrafanacloud_org_metrics_overage{}<br>\ngrafanacloud_instance_billable_usage{} > 0<br>\ngrafanacloud_instance_samples_per_second{}<br>\ngrafanacloud_org_metrics_included_dpm_per_series{}<br>\ngrafanacloud_instance_info{}<br>\n</p>\n"
   }
  },
  { "title": "Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "grafanacloud_org_metrics_billable_series{}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{ }",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "grafanacloud_org_metrics_overage{  } ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage{ } ",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "grafanacloud_instance_billable_usage{ } > 0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "grafanacloud_instance_billable_usage{  } > 0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "grafanacloud_instance_samples_per_second{ }",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "grafanacloud_instance_samples_per_second{ }",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "grafanacloud_org_metrics_included_dpm_per_series{}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_included_dpm_per_series{}",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "grafanacloud_instance_info{ }",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    { "expr": "grafanacloud_instance_info{ }", "legendFormat": "__auto" }
   ]
  },
  { "title": "Work In Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "grafanacloud_instance_info{  }",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "grafanacloud_instance_info{ type=\"prometheus\" }",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}