{
 "title": "0000 - Cost Management - Visualize Usage Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "grafanacloud_org_metrics_billable_series{}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{ }",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "grafanacloud_instance_billable_usage{ } > 0",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "grafanacloud_instance_billable_usage{  } > 0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "grafanacloud_org_metrics_overage{  } ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage{ } ",
     "legendFormat": "Cost"
    }
   ]
  },
  {
   "title": "grafanacloud_instance_samples_per_second{ }",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "grafanacloud_instance_samples_per_second{ }",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "grafanacloud_org_metrics_included_dpm_per_series{}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_included_dpm_per_series{}",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "grafanacloud_instance_info{ }",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "grafanacloud_instance_info{ }", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Work In Progress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "grafanacloud_instance_info{ }",
     "type": "table",
     "gridPos": { "h": 9, "w": 23, "x": 1, "y": 15 },
     "targets": [
      { "expr": "grafanacloud_instance_info{ }", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "grafanacloud_instance_info{  }",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "grafanacloud_instance_info{ type=\"prometheus\" }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}