{
 "title": "Cost Mgt - Final Build",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "VAR_ENV",
    "label": "Environment",
    "query": {
     "query": "label_values(grafanacloud_instance_info{name=~\".*prom.*\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Billable Series",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Billable series metrics count\ngrafanacloud_org_metrics_billable_series{ }",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "Total Billable Series Cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Billable Series Cost\nsum( grafanacloud_org_metrics_overage{} )",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "Change %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "# Calculate the percentage change across the time range\n( grafanacloud_org_metrics_billable_series{ }  @ end() - grafanacloud_org_metrics_billable_series{ } @ start() )\n/ grafanacloud_org_metrics_billable_series{ } @ end()",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "Cost Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "# Cost impact of change in Billiable Series for the Organization\nsum( grafanacloud_org_metrics_billable_series{ } @end() -  grafanacloud_org_metrics_billable_series{ } @start())\n/ sum( grafanacloud_org_metrics_billable_series{} )\n* sum( grafanacloud_org_metrics_overage{} )",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "# Calculate the change across the time range\nsum( grafanacloud_org_metrics_billable_series{ }  @end() - grafanacloud_org_metrics_billable_series{ } @start() )",
     "legendFormat": "Change"
    },
    {
     "expr": "sum( grafanacloud_org_metrics_billable_series{ } @start() )",
     "legendFormat": "Start"
    },
    {
     "expr": "sum( grafanacloud_org_metrics_billable_series{ } @end() )",
     "legendFormat": "End"
    }
   ]
  },
  {
   "title": "Billable Series Per Environment (Selectable)",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "# Calculate the Billable Series Count for each environment\nsort_desc( \n  sum by ( name ) (\n    grafanacloud_instance_billable_usage{}\n    * on (id) group_left( name ) grafanacloud_instance_info{ name=~\".*prom.*\"   }\n  ) > 0 )",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Calculate the Series Cost for each environment: (I / O) * OC\nsort_desc( ( (\n      max( grafanacloud_instance_billable_usage{} ) by (id) > 0 ) # Stacks' BillableSeries, where > 0\n      / ignoring(id) group_left() # Divided by Org BillableSeries\n        max(grafanacloud_org_metrics_billable_series{}) by (id)\n  ) * on (id) group_left(name) \n      max by(id, name) (grafanacloud_instance_info{ name=~\".*prom.*\" })\n) * on () group_left() sum (grafanacloud_org_metrics_overage{} ) # Org-wide Metrics bill, dollars:",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Billable change % for each individual environment\nsort_desc(\n  sum by ( name ) (\n      ((grafanacloud_instance_billable_usage{} @end() > 0) - grafanacloud_instance_billable_usage{} @start())\n        / grafanacloud_instance_billable_usage{} @end()\n        * on (id) group_left( name ) grafanacloud_instance_info{ name=~\".*prom.*\" } ) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Cost impact to individual environment of change in active series\nsort_desc(\n  sum by ( name ) (\n     ( (grafanacloud_instance_billable_usage{} @end() > 0) - grafanacloud_instance_billable_usage{} @start() )\n        / on (org_id) group_left( name ) grafanacloud_org_metrics_billable_series{} \n        * on (org_id) group_left( name ) grafanacloud_org_metrics_overage{} \n        * on (id) group_left( name ) grafanacloud_instance_info{ name=~\".*prom.*\" } ) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Billable Series",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 2 },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series{ }",
     "legendFormat": "Billable Series"
    }
   ]
  },
  {
   "title": "Environment: $VAR_ENV",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "# Filter using a dashboard variable: $VAR_ENV the instance billable usage\nsum by ( name ) (\n    grafanacloud_instance_billable_usage{}\n    * on (id) group_left( name ) grafanacloud_instance_info{ name=~\"$VAR_ENV\"   }\n  ) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cost-mgt-billable-series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "cost_mgt_billable_series:predicted"
    },
    {
     "expr": "cost_mgt_billable_series:actual"
    },
    {
     "expr": "cost_mgt_billable_series:anomalous",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Billing Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 10, "x": 13, "y": 12 } }
 ]
}